#!/bin/sh

picom &

udiskie-mount --all &

xset -dpms &
xset s off &
xsetroot -cursor_name left_ptr &

feh --bg-fill ~/wallpaper.jpg &

xset b off &
xhost +SI:localuser:$USER &
export _JAVA_AWT_WM_NONREPARENTING=1 &
xset r rate 200 60 &

# odd issue with programs taking too long to launch
systemctl --user import-environment DISPLAY XAUTHORITY &
dbus-update-activation-environment DISPLAY XAUTHORITY &

dunst &

xfce4-session &

exec i3
