#!/bin/sh

picom &

udiskie-mount --all &

xset -dpms &
xset s off &
xsetroot -cursor_name left_ptr &

feh --bg-fill ~/wallpapers/x220.png &

# odd issue with programs taking too long to launch
systemctl --user import-environment DISPLAY XAUTHORITY &
dbus-update-activation-environment DISPLAY XAUTHORITY &

dunst &

xfce4-session &

setxkbmap -layout us -model thinkpad60 -variant dvp -option lv3:ralt_switch &

exec /usr/bin/xmonad 
