#!/bin/sh

[[ -f ~/.Xresources ]] && xrdb -merge -I$HOME ~/.Xresources

picom &

udiskie-mount --all &

xset -dpms &
xset s off &
xsetroot -cursor_name left_ptr &

feh --bg-fill ~/wallpapers/x220.png

# odd issue with programs taking too long to launch
systemctl --user import-environment DISPLAY XAUTHORITY
dbus-update-activation-environment DISPLAY XAUTHORITY

dunst &
sxhkd &

xfce4-session &

/usr/bin/xmonad
