--vim.cmd [[autocmd FileType netrw setl bufhidden=wipe]]
--Bind('', '<Space>', '<Nop>', Opts)
Bind('n', '<leader>,', ':lua vim.lsp.buf.format() <CR>', Opts)
--Bind('n', '<leader>g', ':TermExec cmd=lazygit <CR>', Opts)
--
---- Better window navigation
--Bind('n', '<C-h>', '<C-w>h', Opts)
--Bind('n', '<C-j>', '<C-w>j', Opts)
--Bind('n', '<C-k>', '<C-w>k', Opts)
--Bind('n', '<C-l>', '<C-w>l', Opts)
--
---- ccc
--Bind('n', '<leader>p', ':CccPick <CR>', Opts)
--
---- undo tree
--Bind('n', '<leader>u', ':UndotreeToggle <CR>', Opts)
--
---- netwr
--Bind('n', '<leader>.', ':Telescope file_browser hidden=true <CR>', Opts)
--
---- MD preview
--Bind('n', '<leader>wp', ':MarkdownPreviewToggle <CR>', Opts)
